### ISSUE TITLE
Error when tried to create a element:repo

### ISSUE THREAD

**Issue by cadwmaster** [webcomponents/generator-element#26]
After asking for the github path the generator exit with this error:

/usr/local/lib/node_modules/generator-element/repo/index.js:65
                    if (!available.bower) {
                                  ^
TypeError: Cannot read property 'bower' of undefined
    at /usr/local/lib/node_modules/generator-element/repo/index.js:65:35
    at /usr/local/lib/node_modules/generator-element/node_modules/pkg-name/index.js:25:4
    at callback (/usr/local/lib/node_modules/generator-element/node_modules/pkg-name/node_modules/each-async/index.js:33:4)
    at /usr/local/lib/node_modules/generator-element/node_modules/pkg-name/node_modules/each-async/node_modules/onetime/index.js:20:12
    at /usr/local/lib/node_modules/generator-element/node_modules/pkg-name/index.js:16:5
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/generator-element/node_modules/pkg-name/node_modules/npm-name/index.js:13:4)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.emit (events.js:95:17)
    at Socket.socketErrorListener (http.js:1551:9)
    at Socket.emit (events.js:95:17)

**Comment by zenorocha** [comment]
Have you tried a `npm cache clean` before installing it? It seems like it didn't install of the dependencies then.

**Comment by cadwmaster** [comment]
No, same error :(

![screen shot 2015-01-16 at 12 21 12 pm](https://cloud.githubusercontent.com/assets/3181532/5775452/4b296b72-9d7a-11e4-93b1-c0183c4b86a9.png)

**Comment by zenorocha** [comment]
@betomuniz can you check that?

**Comment by obetomuniz** [comment]
@zenorocha yes!

**Comment by darrenoh** [comment]
Why hasn’t this been re-opened?
